## This is test deployment for Kubernetes platforms.
## This is _not_ intended to be used in production.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-memcached-exporter
  name: test-memcached-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-memcached-exporter
  template:
    metadata:
      labels:
        app: test-memcached-exporter
    spec:
      containers:
      - image: bitnami/memcached-exporter
        name: memcached-exporter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-memcached-exporter
  name: test-memcached-exporter
spec:
  ports:
  - port: 9150
    protocol: TCP
    targetPort: 9150
  selector:
    app: test-memcached-exporter
  sessionAffinity: None
  type: ClusterIP
